### PR TITLE
feat: add execa@9.5.2

### PR DESCRIPTION
**Pull request by kastov**
Hi!

I have added [execa@9.5.2](https://github.com/sindresorhus/execa).

Not sure that it will work as expected, need testing.

### CODE REVIEW

**Comment by isaachinman** [comment]
Do you use that package? If so, you can test yourself by copying or symlinking the dist files here.

**Comment by kastov** [comment]
> Do you use that package? If so, you can test yourself by copying or symlinking the dist files here.

Yep, i updated to proper imports. 

I have tested and in my case seems like works fine.

**Comment by kastov** [comment]
> Do you use that package? If so, you can test yourself by copying or symlinking the dist files here.

Hi again! I made more tests and all is good. 
I have setup Execa in one of my projects with NestJS (CommonJS), no issues found.

**Comment by isaachinman** [comment]
Thanks. Can you please follow the export pattern here?

https://github.com/sindresorhus/execa/blob/main/index.js

We should avoid namespace exports as they cause trouble with bundlers.

**Comment by kastov** [comment]
> Thanks. Can you please follow the export pattern here?
> 
> https://github.com/sindresorhus/execa/blob/main/index.js
> 
> We should avoid namespace exports as they cause trouble with bundlers.

```
import {
  execa,
  execaSync,
  execaCommand,
  execaCommandSync,
  execaNode,
  $,
  ExecaError,
  ExecaSyncError,
  parseCommandString,
  sendMessage,
  getOneMessage,
  getEachMessage,
  getCancelSignal,
} from 'execa'


export {
  execa,
  execaSync,
  execaCommand,
  execaCommandSync,
  execaNode,
  $,
  ExecaError,
  ExecaSyncError,
  parseCommandString,
  sendMessage,
  getOneMessage,
  getEachMessage,
  getCancelSignal,
}
```

Something like that?

**Comment by isaachinman** [comment]
Yep, however the original package has structured its exports.

**Comment by kastov** [comment]
> Yep, however the original package has structured its exports.

```
import {
  execa as execaOriginal,
  execaSync as execaSyncOriginal,
  execaCommand as execaCommandOriginal,
  execaCommandSync as execaCommandSyncOriginal,
  execaNode as execaNodeOriginal,
  $ as $Original,
  ExecaError,
  ExecaSyncError,
  parseCommandString,
  sendMessage,
  getOneMessage,
  getEachMessage,
  getCancelSignal,
} from 'execa'

export { parseCommandString }
export { ExecaError, ExecaSyncError }

export const execa = execaOriginal
export const execaSync = execaSyncOriginal
export const execaCommand = execaCommandOriginal
export const execaCommandSync = execaCommandSyncOriginal
export const execaNode = execaNodeOriginal
export const $ = $Original
export { sendMessage, getOneMessage, getEachMessage, getCancelSignal }
```

**Comment by isaachinman** [comment]
Yes, exactly.

**Comment by kastov** [comment]
> Yes, exactly.

Good! Updated.

**Comment by isaachinman** [comment]
Published here:

https://www.npmjs.com/package/@cjs-exporter/execa

Thanks @kastov!

**Pull request merged**
